name = "sanjay-pages-dev"
compatibility_date = "2024-10-01"
pages_build_output_dir = "."

[vars]
# Local dev only; set real values in Cloudflare Pages dashboard for production
ADMIN_USER = "sagar"
ADMIN_PASS = "sagar12390"

